import "./css/style.css";
import header from "./components/header";
import main from "./components/main";
import taskManager from "./components/TaskManager";
import projectManager from "./components/projectManager";
import aside from "./components/aside";
const app = document.querySelector(".app");
app.appendChild(header());
app.appendChild(main());
app.appendChild(aside());
taskManager.showTasks();
projectManager.showProjects();
