import "./css/style.css";
import header from "./components/header";
import main from "./components/main";
import Project from "./components/Project";
import aside from "./components/aside";
import currentProject from "./components/currentProject";
import projectManager from "./components/projectManager";
const app = document.querySelector(".app");
app.appendChild(header());
app.appendChild(main());
app.appendChild(aside());
projectManager.addProject("today");
const today = projectManager.getProject("today");
currentProject.project = today;
currentProject.project.tm.showTasks();
